### ISSUE TITLE
Feature Request: Scrobbler support for Libre.fm, Last.fm, ...

### ISSUE THREAD

**Issue by bobcanthelpyou** [nazar-pc/CleverStyle-Music#18]
It would be great if scrobbling support could be added to your CleverStyle-Music player.

http://www.last.fm/api/authentication
http://www.last.fm/api/scrobbling

If that feature could be useful for your CleverStyle-Music player, i maybe could support with coding.

**Comment by nazar-pc** [comment]
If someone needs this - it will be useful. Feel free to send pull request or ask questions, any help is highly appreciated.
