### ISSUE TITLE
Flac files not found on Flame device (Firefox 1.3 ).

### ISSUE THREAD

**Issue by inkhey** [nazar-pc/CleverStyle-Music#3]
This application don't support flac on my device (Flame).
It work exactly the same as the standard «music» application that don't support also Flac, flac files are just not found and not add to music library.

**Comment by ElPopi** [comment]
First of all:Thank you for the app. I'm having the same issue on a ZTE open2, so I put my vote on bugzilla. I hope it will fixed soon.
