### ISSUE TITLE
Cover.jpg not supported as cover album

### ISSUE THREAD

**Issue by inkhey** [nazar-pc/CleverStyle-Music#4]
Same problem as : https://bugzilla.mozilla.org/show_bug.cgi?id=1060331

Steps to reproduce:

1.Create a music album folder on computer with music files (with no cover album tag) and cover.jpg file as album cover.
2.Transfer this folder to Flame device .
3.Open CleverStyle-Music application on Flame device.

Actual results:

There is no detected album cover .

Expected results:

I should have a cover album (cover.jpg) for music files that are in the same folder as cover.jpg.

This "trick" work fine on my walkman and on computer program like Rhythmbox on linux.

**Comment by petrica-celrau** [comment]
Thank you for this app, the equalizer is what I needed. 
A few notes (for reference I use a Open C with v2.1 on JB base):
-for some reason the base volume is like half way lower then with the stock music app
-could you also implement lockscreen controls (stop/start/etc.)?
-maybe the equalizer needs a reset button
I cannot code so I can only help with suggestions and/or testing.

**Comment by nazar-pc** [comment]
@inkhey, it was a long way, but I have some time last days.
Now player works with `sdcard` storage instead of `music`, which means that we now have access to files of any type.
Covers should be in Git version in few days.

**Comment by nazar-pc** [comment]
Implemented with 84eea06, please, check it
